## Library import

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
import warnings
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report
warnings.filterwarnings('ignore')

## Data import

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/06_CHURN_PREDICTION/customer_churn.csv')

## EDA(exploratory data analysis)

In [4]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [6]:
df.shape

(7043, 21)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

**TotalCharges is in Object datatype**

In [8]:
df.drop('customerID',axis = 1,inplace = True)

In [9]:
df.TotalCharges.unique()

array(['29.85', '1889.5', '108.15', ..., '346.45', '306.6', '6844.5'],
      dtype=object)

In [10]:
df[pd.to_numeric(df.TotalCharges,errors='coerce').isnull()]

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,Male,0,No,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,Female,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [11]:
df[pd.to_numeric(df.TotalCharges,errors='coerce').isnull()].shape

(11, 20)

In [12]:
df1 = df[df.TotalCharges != ' ']

In [13]:
df1.TotalCharges = pd.to_numeric(df1.TotalCharges)
df1.TotalCharges.dtypes

dtype('float64')

In [14]:
def print_unique_val(df):
    for col in df:
        if df[col].dtypes == 'object':
            print(f'{col}:{df[col].unique()}')

In [15]:
print_unique_val(df1)

gender:['Female' 'Male']
Partner:['Yes' 'No']
Dependents:['No' 'Yes']
PhoneService:['No' 'Yes']
MultipleLines:['No phone service' 'No' 'Yes']
InternetService:['DSL' 'Fiber optic' 'No']
OnlineSecurity:['No' 'Yes' 'No internet service']
OnlineBackup:['Yes' 'No' 'No internet service']
DeviceProtection:['No' 'Yes' 'No internet service']
TechSupport:['No' 'Yes' 'No internet service']
StreamingTV:['No' 'Yes' 'No internet service']
StreamingMovies:['No' 'Yes' 'No internet service']
Contract:['Month-to-month' 'One year' 'Two year']
PaperlessBilling:['Yes' 'No']
PaymentMethod:['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
Churn:['No' 'Yes']

In [16]:
df1.replace('No internet service','No',inplace = True)
df1.replace('No phone service','No',inplace = True)

In [17]:
print_unique_val(df1)

gender:['Female' 'Male']
Partner:['Yes' 'No']
Dependents:['No' 'Yes']
PhoneService:['No' 'Yes']
MultipleLines:['No' 'Yes']
InternetService:['DSL' 'Fiber optic' 'No']
OnlineSecurity:['No' 'Yes']
OnlineBackup:['Yes' 'No']
DeviceProtection:['No' 'Yes']
TechSupport:['No' 'Yes']
StreamingTV:['No' 'Yes']
StreamingMovies:['No' 'Yes']
Contract:['Month-to-month' 'One year' 'Two year']
PaperlessBilling:['Yes' 'No']
PaymentMethod:['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
Churn:['No' 'Yes']

In [18]:
yes_no_cols = ['Partner','Dependents','PhoneService','MultipleLines',
              'OnlineSecurity','OnlineBackup','DeviceProtection',
              'TechSupport','StreamingTV','StreamingMovies',
              'PaperlessBilling','Churn']
for col in yes_no_cols:
    df1[col].replace({'Yes':1,'No':0},inplace = True)

In [19]:
print_unique_val(df1)

gender:['Female' 'Male']
InternetService:['DSL' 'Fiber optic' 'No']
Contract:['Month-to-month' 'One year' 'Two year']
PaymentMethod:['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

In [20]:
df1.gender.replace({'Female':1,'Male':0},inplace = True)

In [21]:
print_unique_val(df1)

InternetService:['DSL' 'Fiber optic' 'No']
Contract:['Month-to-month' 'One year' 'Two year']
PaymentMethod:['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

In [22]:
df2 = pd.get_dummies(data = df1,
                     columns=['InternetService','Contract','PaymentMethod']).astype(int)
df2.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'PaperlessBilling', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'Contract_Month-to-month', 'Contract_One year',
       'Contract_Two year', 'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')

In [23]:
df2.sample(2)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,InternetService_DSL,InternetService_Fiber optic,InternetService_No,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
3449,1,0,1,1,52,1,1,0,1,1,...,0,1,0,0,1,0,0,1,0,0
5030,0,0,0,1,6,1,0,0,0,1,...,0,1,0,1,0,0,0,0,0,1

In [24]:
df2.dtypes

gender                                     int64
SeniorCitizen                              int64
Partner                                    int64
Dependents                                 int64
tenure                                     int64
PhoneService                               int64
MultipleLines                              int64
OnlineSecurity                             int64
OnlineBackup                               int64
DeviceProtection                           int64
TechSupport                                int64
StreamingTV                                int64
StreamingMovies                            int64
PaperlessBilling                           int64
MonthlyCharges                             int64
TotalCharges                               int64
Churn                                      int64
InternetService_DSL                        int64
InternetService_Fiber optic                int64
InternetService_No                         int64
Contract_Month-to-month                    int64
Contract_One year                          int64
Contract_Two year                          int64
PaymentMethod_Bank transfer (automatic)    int64
PaymentMethod_Credit card (automatic)      int64
PaymentMethod_Electronic check             int64
PaymentMethod_Mailed check                 int64
dtype: object

In [25]:
col_to_scale = ['tenure','MonthlyCharges','TotalCharges']

In [26]:
scale = MinMaxScaler()

In [27]:
df2[col_to_scale] = scale.fit_transform(df2[col_to_scale])

In [28]:
x = df2.drop('Churn',axis = 1)
y = df2.Churn.astype(float)

In [29]:
y.value_counts()

Churn
0.0    5163
1.0    1869
Name: count, dtype: int64

## Train Test Split

In [30]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state = 15,test_size = 0.2)

In [31]:
y_train.value_counts()

Churn
0.0    4123
1.0    1502
Name: count, dtype: int64

In [32]:
y_test.value_counts()

Churn
0.0    1040
1.0     367
Name: count, dtype: int64

In [33]:
x_test.shape

(1407, 26)

In [34]:
x_train.shape

(5625, 26)

## LOGISTIC REGRESSION

In [37]:
def log_reg(x_train,x_test,y_train,y_test,weights):
    if weights == -1:
        model = LogisticRegression()
    else:
        model = LogisticRegression(class_weight={0:weights[0],1:weights[1]})
    model.fit(x_train,y_train)
    acc = model.score(x_test,y_test)
    print('Accuracy:',acc,'\n')
    y_pred = model.predict(x_test)
    class_repo = classification_report(y_test,y_pred)
    print(class_repo)

In [38]:
weights = -1
log_reg(x_train,x_test,y_train,y_test,weights)

Accuracy: 0.8152096659559346

              precision    recall  f1-score   support

         0.0       0.85      0.91      0.88      1040
         1.0       0.69      0.54      0.60       367

    accuracy                           0.82      1407
   macro avg       0.77      0.73      0.74      1407
weighted avg       0.81      0.82      0.81      1407

In [39]:
weights = [1,1.5]
log_reg(x_train,x_test,y_train,y_test,weights)

Accuracy: 0.7931769722814499

              precision    recall  f1-score   support

         0.0       0.87      0.85      0.86      1040
         1.0       0.60      0.64      0.62       367

    accuracy                           0.79      1407
   macro avg       0.73      0.74      0.74      1407
weighted avg       0.80      0.79      0.80      1407

## Under Sampling

In [40]:
count_0,count_1 = df2.Churn.value_counts()
print(count_0,count_1)

5163 1869

In [42]:
df_0 = df2[df2.Churn == 0]
df_1 = df2[df2.Churn == 1]
print(df_0.shape,df_1.shape)
df_0_under = df_0.sample(count_1)
print(df_0_under.shape)

(5163, 27) (1869, 27)
(1869, 27)

In [43]:
df_under_sample = pd.concat([df_0_under,df_1],axis = 0)
print('After Under sampling:\n')
print(df_under_sample.Churn.value_counts())

After Under sampling:

Churn
0    1869
1    1869
Name: count, dtype: int64

In [44]:
x = df_under_sample.drop('Churn',axis = 1)
y = df_under_sample.Churn

In [45]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state =15,test_size = 0.2,stratify = y)

In [46]:
y_train.value_counts()

Churn
0    1495
1    1495
Name: count, dtype: int64

In [48]:
y_test.value_counts()

Churn
1    374
0    374
Name: count, dtype: int64

In [49]:
weights = -1
log_reg(x_train,x_test,y_train,y_test,weights)

Accuracy: 0.7513368983957219

              precision    recall  f1-score   support

           0       0.76      0.73      0.75       374
           1       0.74      0.77      0.76       374

    accuracy                           0.75       748
   macro avg       0.75      0.75      0.75       748
weighted avg       0.75      0.75      0.75       748

In [50]:
weights = [1,1.5]
log_reg(x_train,x_test,y_train,y_test,weights)

Accuracy: 0.7486631016042781

              precision    recall  f1-score   support

           0       0.81      0.64      0.72       374
           1       0.71      0.85      0.77       374

    accuracy                           0.75       748
   macro avg       0.76      0.75      0.75       748
weighted avg       0.76      0.75      0.75       748

## OverSampling

In [51]:
df_1_over = df_1.sample(count_0,replace = True)
df_over = pd.concat([df_0,df_1_over],axis = 0)

In [52]:
df_over.Churn.value_counts()

Churn
0    5163
1    5163
Name: count, dtype: int64

In [53]:
x = df_over.drop('Churn',axis = 1)
y = df_over.Churn

In [54]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state =15,test_size = 0.2,stratify = y)

In [55]:
y_train.value_counts()

Churn
1    4130
0    4130
Name: count, dtype: int64

In [56]:
y_test.value_counts()

Churn
1    1033
0    1033
Name: count, dtype: int64

In [57]:
weights = -1
log_reg(x_train,x_test,y_train,y_test,weights)

Accuracy: 0.755082284607938

              precision    recall  f1-score   support

           0       0.77      0.72      0.75      1033
           1       0.74      0.79      0.76      1033

    accuracy                           0.76      2066
   macro avg       0.76      0.76      0.75      2066
weighted avg       0.76      0.76      0.75      2066

## SMOTE

In [60]:
from imblearn.over_sampling import SMOTE

In [63]:
x = df2.drop('Churn',axis = 1)
y = df2.Churn

In [64]:
smote = SMOTE(sampling_strategy = 'minority')
x_sm,y_sm = smote.fit_resample(x,y)

In [65]:
y_sm.value_counts()

Churn
0    5163
1    5163
Name: count, dtype: int64

In [67]:
x_train,x_test,y_train,y_test = train_test_split(x_sm,y_sm,random_state =15,test_size = 0.2,stratify = y_sm)

In [68]:
weights = -1
log_reg(x_train,x_test,y_train,y_test,weights)

Accuracy: 0.7996127783155856

              precision    recall  f1-score   support

           0       0.82      0.77      0.79      1033
           1       0.78      0.83      0.80      1033

    accuracy                           0.80      2066
   macro avg       0.80      0.80      0.80      2066
weighted avg       0.80      0.80      0.80      2066

## Ensemble

In [70]:
df2.Churn.value_counts()

Churn
0    5163
1    1869
Name: count, dtype: int64

In [71]:
x = df2.drop('Churn',axis = 1)
y = df2.Churn

In [72]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state =15,test_size = 0.2,stratify = y)

In [73]:
y_train.value_counts()

Churn
0    4130
1    1495
Name: count, dtype: int64

model1 --> class1(1495) + class0(0, 1495)

model2 --> class1(1495) + class0(1496, 2990)

model3 --> class1(1495) + class0(2990, 4130)

In [74]:
model = LogisticRegression()
df3 = x_train.copy()
df3['Churn'] = y_train

In [75]:
df3.sample(3)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,InternetService_Fiber optic,InternetService_No,Contract_Month-to-month,Contract_One year,Contract_Two year,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn
4751,0,0,0,0,0.140845,1,1,0,0,0,...,0,1,1,0,0,0,1,0,0,1
4699,1,0,1,0,0.676056,1,1,1,1,1,...,1,0,0,0,1,0,1,0,0,0
1052,1,0,0,0,0.549296,1,1,0,0,1,...,0,0,0,1,0,0,0,0,1,0

In [76]:
df_0 = df3[df3.Churn == 0]
df_1 = df3[df3.Churn == 1]

In [77]:
def get_train_batch(df_major,df_minor,start,end):
    df_train = pd.concat([df_major[start:end],df_minor],axis = 0)
    x_train = df_train.drop('Churn',axis = 1)
    y_train = df_train.Churn
    return x_train,y_train

In [80]:
x_train,y_train = get_train_batch(df_0,df_1,0,1495)

In [81]:
model1 = LogisticRegression()
model1.fit(x_train, y_train)
y_pred1 = model1.predict(x_test)

In [84]:
x_train,y_train = get_train_batch(df_0,df_1,1495,2990)
model2 = LogisticRegression()
model2.fit(x_train, y_train)
y_pred2 = model1.predict(x_test)

In [85]:
x_train,y_train = get_train_batch(df_0,df_1,2990,4130)
model3 = LogisticRegression()
model3.fit(x_train, y_train)
y_pred3 = model1.predict(x_test)

In [86]:
y_pred_final = y_pred1.copy()
for i in range(len(y_pred1)):
    n_ones = y_pred1[i] + y_pred2[i] + y_pred3[i]
    if n_ones>1:
        y_pred_final[i] = 1
    else:
        y_pred_final[i] = 0

In [87]:
print(classification_report(y_test,y_pred_final))

              precision    recall  f1-score   support

           0       0.90      0.73      0.81      1033
           1       0.52      0.79      0.62       374

    accuracy                           0.75      1407
   macro avg       0.71      0.76      0.72      1407
weighted avg       0.80      0.75      0.76      1407